// ONLY include the card result_edition UUID
export default [{
  setCode: 'DOAp',
  filename: 'lorraine-starter-deck',
  name: 'Lorraine Starter Deck',
  isDeck: true,
  cards: [{
    id: '3051lmd58M',
    quantity: 1,
  },  {
    id: 'dPtl3qCIug',
    quantity: 1,
  },  {
    id: 'bPllVQlUQX',
    quantity: 1,
  },  {
    id: 'OKOTXSMM5P',
    quantity: 1,
  },  {
    id: 'MlMGQjYJls',
    quantity: 1,
  },  {
    id: 'vyy7Qes4xf',
    quantity: 1,
  },  {
    id: 'x3zyuBNcYj',
    quantity: 1,
  },  {
    id: 'KIGZ7N8ajb',
    quantity: 1,
  },  {
    id: 'Cd1nKGvvbR',
    quantity: 1,
  },  {
    id: 'DegP154SpL',
    quantity: 1,
  },  {
    id: '4F2qOhesWT',
    quantity: 1,
  },  {
    id: 'rlsfzjgjbN',
    quantity: 1,
  },  {
    id: 'O2m7mGRAeR',
    quantity: 3,
  },  {
    id: 'NmkpuQS9yy',
    quantity: 4,
  },  {
    id: 'MpIDRIgOoI',
    quantity: 3,
  }, {
    id: 'rD0ru89aOn',
    quantity: 2,
  }, {
    id: 'mZdILhIEge',
    quantity: 4,
  }, {
    id: 'yRV4meY2cI',
    quantity: 4,
  }, {
    id: 't5FccCR8Y0',
    quantity: 4,
  }, {
    id: '7mDZsY8mXV',
    quantity: 3,
  }, {
    id: 'ctVRMYgJdw',
    quantity: 2,
  }, {
    id: 'PT8qGktvHO',
    quantity: 3,
  }, {
    id: 'TGRgLqBWDV',
    quantity: 2,
  }, {
    id: 'mLsQ49MEEH',
    quantity: 4,
  }, {
    id: '35qxrG1FtQ',
    quantity: 2,
  }, {
    id: 'GdVntFV7w2',
    quantity: 1,
  }, {
    id: 'seHW4HxE03',
    quantity: 2,
  }, {
    id: 'TaFgPIb2RJ',
    quantity: 3,
  }, {
    id: 'FYQMG2LxpG',
    quantity: 2,
  }, {
    id: 'N1xJGsK4Xc',
    quantity: 4,
  }, {
    id: 'sxUsVgyBBJ',
    quantity: 3,
  }, {
    id: '3unQU3mKi6',
    quantity: 2,
  }, {
    id: '02yhNm2ejR',
    quantity: 1,
  }]
}, {
  setCode: 'DOAp',
  filename: 'rai-starter-deck',
  name: 'Rai Starter Deck',
  isDeck: true,
  cards: [{
    id: '1tisZwrn8k',
    quantity: 1,
  }, {
    id: 'T8HANtcnoP',
    quantity: 1,
  }, {
    id: 'k6nRXZI20p',
    quantity: 1,
  }, {
    id: '4pG2R8Qegg',
    quantity: 1,
  }, {
    id: 'nmVuReXiZb',
    quantity: 1,
  }, {
    id: 'YmZbYNgyz1',
    quantity: 1,
  }, {
    id: '7CN2tvJWwH',
    quantity: 1,
  }, {
    id: '6ed9UtJxKg',
    quantity: 1,
  }, {
    id: 'gtPUR2RQc8',
    quantity: 1,
  }, {
    id: 'DegP154SpL',
    quantity: 1,
  }, {
    id: 'EvKTV50R5p',
    quantity: 1,
  }, {
    id: 'SdNchmW1Cs',
    quantity: 1,
  }, {
    id: 'kGdhXWvHFi',
    quantity: 2,
  }, {
    id: 'rD0ru89aOn',
    quantity: 2,
  }, {
    id: 'gP2rko32Mc',
    quantity: 3,
  }, {
    id: 'A0IGBIN2d8',
    quantity: 4,
  }, {
    id: 'clY8HapI0j',
    quantity: 3,
  }, {
    id: 'LRcxPAyqLu',
    quantity: 3,
  }, {
    id: 'yYALePKMk8',
    quantity: 4,
  }, {
    id: 'oJxHM7bFVy',
    quantity: 2,
  }, {
    id: '0dQdTTkzj5',
    quantity: 4,
  }, {
    id: 'ePlzjNiNpy',
    quantity: 4,
  }, {
    id: 'Wsb1PlS8vT',
    quantity: 4,
  }, {
    id: 'iXtv9R9vVn',
    quantity: 2,
  }, {
    id: '3mJsa4iMp7',
    quantity: 4,
  }, {
    id: '8TSQJQQ6gB',
    quantity: 4,
  }, {
    id: 'kJgwjVO3eV',
    quantity: 2,
  }, {
    id: 'lr7hqOfc54',
    quantity: 4,
  }, {
    id: 'oK7dgm60MK',
    quantity: 1,
  }, {
    id: 'PnStg7sP1T',
    quantity: 2,
  }, {
    id: 'mLsQ49MEEH',
    quantity: 4,
  }, {
    id: 'UM5gNZA4MT',
    quantity: 2,
  }]
}, {
  setCode: 'DOAp',
  filename: 'kickstarter-exclusive',
  name: 'Kickstarter exclusive',
  isDeck: false,
  cards: [{
    id: 'X8nzLt8g3A',
  }, {
    id: 'Woa1K0GUWh',
  }, {
    id: 'DMZJI3Ahw8',
  }, {
    id: 'TqCcJoJ1jP',
  }, {
    id: 'a2NCLoSyXC',
  }, {
    id: 'WaxfxF6gKQ',
  }, {
    id: 'zPLTy7x1XL',
  }, {
    id: 'P7HUyoVVKD',
  }, {
    id: 'VhnWSG9ylR',
  }, {
    id: 'grZJAjxXXi',
  }, {
    id: 'zFDWR3ZzQV',
  }, {
    id: 'GGqvrmxp8Y',
  }, {
    id: 'KSKbpeiFQR',
  }, {
    id: 'VqA6aSalXw',
  }, {
    id: 'bZ2tagSaFZ',
  }, {
    id: 'ybT6KGi3Ha',
  }, {
    id: 'JkMKE6adCw',
  }, {
    id: 'TunoowZr48',
  }, {
    id: 'IWj5G7UO24',
  }, {
    id: 'UyNpsv41nN',
  }, {
    id: 'glApsoTUXv',
  }, {
    id: 'kGdhXWvHFi',
  }, {
    id: 'UvDktoulIJ',
  }, {
    id: 'pjvYLaHE1k',
  }, {
    id: 'DOONM8ZQwt',
  }, {
    id: 'H64mP98Ch4',
  }, {
    id: 'qL8RBfLJBy',
  }, {
    id: 'sCeymbd0qF',
  }, {
    id: 'jTz60pxgUk',
  }, {
    id: 'hNbiB57qyJ',
  }, {
    id: 'ZbbeSsnVeU',
  }, {
    id: 'OiOzavefYK',
  }, {
    id: 'iHjJQO9Ff1',
  }, {
    id: 'VSzmyrUmrr',
  }, {
    id: '7h8JzLeWPU',
  }, {
    id: 'aB93Fl6PFL',
  }, {
    id: 'STiZ1fifo0',
  }, {
    id: 'ctVRMYgJdw',
  }, {
    id: 'wUdHOz9NF4',
  }, {
    id: 'AZyC3TllBp',
  }, {
    id: 'afOREBOCmx',
  }, {
    id: 'V6gBBisXz5',
  }, {
    id: 'xRxSDiSKlR',
  }, {
    id: 'ugvzKCILz4',
  }, {
    id: 'dfoXKlqFzL',
  }, {
    id: 'xR2vHpYtzA',
  }, {
    id: 'jr2PgdeTQj',
  }, {
    id: 't3F6t2J2F9',
  }, {
    id: 'oJxHM7bFVy',
  }, {
    id: '7YwfHJaVjZ',
  }, {
    id: 'aKBLFcgUVY',
  }, {
    id: 'j76ffxEal6',
  }, {
    id: 'EtI3gm9YhK',
  }, {
    id: 'D1LJVwFNkh',
  }, {
    id: 'seHW4HxE03',
  }]
}, {
  setCode: 'DOAp',
  filename: 'box-topper',
  name: 'Box topper pack',
  isDeck: true,
  cards: [{
    id: 'TehAgfflE3',
    quantity: 1,
  }, {
    id: 'nKsbvq7izT',
    quantity: 1,
  }, {
    id: 'J7Z6Ksbsox',
    quantity: 1,
  }, {
    id: 'LLgpatiC2S',
    quantity: 1,
  }, {
    id: 'KHxN8Dsm36',
    quantity: 1,
  }, {
    id: '5dnNqK3KZU',
    quantity: 1,
  }]
}, {
  setCode: 'DOA 1st',
  filename: 'box-topper',
  name: 'Box topper pack',
  isDeck: true,
  cards: [{
    id: 'zqHccKpk8L',
    quantity: 2,
  }, {
    id: 'XhpXCItkPe',
    quantity: 2,
  }, {
    id: '1drFujjOnf',
    quantity: 2,
  }]
}, {
  setCode: 'DEMO22',
  filename: 'lgs-demo-deck',
  name: 'LGS Demo Deck',
  isDeck: true,
  cards: [{
    id: 'oBKuCfrxbF',
    quantity: 1,
  }, {
    id: 'RWwB4PfbAT',
    quantity: 1,
  }, {
    id: 'fduy9cy0W3',
    quantity: 1,
  }, {
    id: 'KkmMxafOcd',
    quantity: 1,
  }, {
    id: 'XztBsVXFLP',
    quantity: 1,
  }, {
    id: '34qZzBpnsT',
    quantity: 1,
  }, {
    id: 's5z59BzvFc',
    quantity: 1,
  }, {
    id: '8q9Zd4Pgdl',
    quantity: 1,
  }, {
    id: 'KEpPCif67K',
    quantity: 1,
  }, {
    id: 'lo6bC9AWKJ',
    quantity: 3,
  }, {
    id: 'dkNM9803HT',
    quantity: 2,
  }, {
    id: '2f5KYqY3cv',
    quantity: 3,
  }, {
    id: 'AvZiJFuXvZ',
    quantity: 3,
  }, {
    id: 'OQOAQVzLtd',
    quantity: 2,
  }, {
    id: 'L1PtqiW83n',
    quantity: 3,
  }, {
    id: 'xJv8zc3tTC',
    quantity: 2,
  }, {
    id: 'vpOVdHNJP2',
    quantity: 2,
  }, {
    id: 'VuJ9KdU8pR',
    quantity: 2,
  }, {
    id: 'I04cXSLEah',
    quantity: 2,
  }, {
    id: '8K31b06xIE',
    quantity: 3,
  }]
}]