const nonIndexSets = [];

const TEMP_DISCORD_TOURNAMENT = {
  language: 'EN',
  name: 'Temp Discord Tournament',
  prefix: 'Temp Discord',
}

nonIndexSets.push([
  TEMP_DISCORD_TOURNAMENT,
  {
    cardData: [{
      nonIndexImage: 'https://img.silvie.org/cdn/deck-builder/non-index/DOA_276_Bestial_Frenzy_6f6ce05cef.jpg',
      cost_memory: null,
      cost_reserve: 2,
      durability: null,
      editions: [{
        card_id: 'temp-discord-1',
        circulationTemplates: [{
          foil: false,
          name: 'temp-discord',
          population: -1,
          population_operator: '≈',
          printing: 'false',
          uuid: 'temp-discord',
        }],
        circulations: [],
        collector_number: '276',
        formattedCollectorNumber: '276',
        set: TEMP_DISCORD_TOURNAMENT,
        rarity: 4,
        uuid: 'temp-discord-1',
      }],
      effect: 'Choose one. <span class="effect__label">Class Bonus:</span> Choose up to two instead—<br>•Your champion gets +1 level until end of turn.<br>•Target Beast ally gets +1<span class="effect__icon effect__icon--sword"></span> until end of turn.<br>•Target Beast ally gains <span class="effect__label">cleave</span> until end of turn.',
      effect_raw: 'todo_raw',
      element: 'NORM',
      flavor: 'todo flavor',
      last_update: '2023-01-30T22:00:00.000Z',
      level: null,
      life: null,
      name: 'Bestial Frenzy',
      power: null,
      related_ids: null,
      slug: 'temp-discord-1',
      speed: false,
      subtypes: ['TAMER', 'SKILL'],
      types: ['ACTION'],
      uuid: 'temp-discord-1',
    }, {
      nonIndexImage: 'https://img.silvie.org/cdn/deck-builder/non-index/DOA_277_Spark_Fairy_f8590d4169.jpg',
      cost_memory: null,
      cost_reserve: 3,
      durability: null,
      editions: [{
        card_id: 'temp-discord-2',
        circulationTemplates: [{
          foil: false,
          name: 'temp-discord',
          population: -1,
          population_operator: '≈',
          printing: 'false',
          uuid: 'temp-discord',
        }],
        circulations: [],
        collector_number: '277',
        formattedCollectorNumber: '277',
        set: TEMP_DISCORD_TOURNAMENT,
        rarity: 4,
        uuid: 'temp-discord-2',
      }],
      effect: '<span class="effect__label">Stealth</span> <span class="effect__reminder">(This unit can\'t be targeted by attacks unless permitted by <span class="effect__label">true sight</span>.)</span><br><span class="effect__label">On Enter:</span> Target non-champion object gains "At the beginning of your recollection phase, deal 1 unpreventable damage to your champion" for as long as you control Spark Fairy.',
      effect_raw: 'todo_raw',
      element: 'FIRE',
      flavor: 'todo flavor',
      level: null,
      last_update: '2023-01-30T22:00:00.000Z',
      life: 2,
      name: 'Spark Fairy',
      power: 1,
      related_ids: null,
      slug: 'temp-discord-2',
      speed: null,
      subtypes: ['MAGE', 'FAIRY'],
      types: ['ALLY'],
      uuid: 'temp-discord-2',
    }, {
      nonIndexImage: 'https://img.silvie.org/cdn/deck-builder/non-index/frostsworn_paladin_db_image_260e12e878.jpg',
      cost_memory: null,
      cost_reserve: 3,
      durability: null,
      editions: [{
        card_id: 'temp-discord-3',
        circulationTemplates: [{
          foil: false,
          name: 'temp-discord',
          population: -1,
          population_operator: '≈',
          printing: 'false',
          uuid: 'temp-discord',
        }],
        circulations: [],
        collector_number: '278',
        formattedCollectorNumber: '278',
        set: TEMP_DISCORD_TOURNAMENT,
        rarity: 2,
        uuid: 'temp-discord-3',
      }],
      effect: '<span class="effect__label">Intercept</span> <span class="effect__reminder">(Whenever your champion is attacked while this ally is awake, you may redirect that attack to this ally.)</span><br><span class="effect__label">On Enter:</span> You may banish a card with <span class="effect__label">floating memory</span> from your graveyard. If you do, draw a card and put a <span class="effect__label">buff</span> counter on Frostsworn Paladin.',
      effect_raw: 'todo_raw',
      element: 'WATER',
      flavor: 'todo flavor',
      last_update: '2023-01-30T22:00:00.000Z',
      level: null,
      life: 3,
      name: 'Frostsworn Paladin',
      power: 2,
      related_ids: null,
      slug: 'temp-discord-3',
      speed: null,
      subtypes: ['CLERIC', 'WARRIOR', 'HUMAN'],
      types: ['ALLY'],
      uuid: 'temp-discord-3',
    }, {
      nonIndexImage: 'https://img.silvie.org/cdn/deck-builder/non-index/nullifying_lantern_db_image_4414249422.jpg',
      cost_memory: 0,
      cost_reserve: null,
      durability: null,
      editions: [{
        card_id: 'temp-discord-4',
        circulationTemplates: [{
          foil: false,
          name: 'temp-discord',
          population: -1,
          population_operator: '≈',
          printing: 'false',
          uuid: 'temp-discord',
        }],
        circulations: [],
        collector_number: '279',
        formattedCollectorNumber: '279',
        set: TEMP_DISCORD_TOURNAMENT,
        rarity: 2,
        uuid: 'temp-discord-4',
      }],
      effect: 'Cards in graveyards are norm element. <span class="effect__reminder">(They are not any other element.)</span>',
      effect_raw: 'todo_raw',
      element: 'NORM',
      flavor: 'todo flavor',
      last_update: '2023-01-30T22:00:00.000Z',
      level: null,
      life: null,
      name: 'Nullifying Lantern',
      power: null,
      related_ids: null,
      slug: 'temp-discord-4',
      speed: null,
      subtypes: ['CLERIC', 'ACCESSORY'],
      types: ['REGALIA', 'ITEM'],
      uuid: 'temp-discord-4',
    }, {
      nonIndexImage: 'https://img.silvie.org/cdn/deck-builder/non-index/young_beastbonder_db_image_25450b122b.jpg',
      cost_memory: null,
      cost_reserve: 2,
      durability: null,
      editions: [{
        card_id: 'temp-discord-5',
        circulationTemplates: [{
          foil: false,
          name: 'temp-discord',
          population: -1,
          population_operator: '≈',
          printing: 'false',
          uuid: 'temp-discord',
        }],
        circulations: [],
        collector_number: '280',
        formattedCollectorNumber: '280',
        set: TEMP_DISCORD_TOURNAMENT,
        rarity: 2,
        uuid: 'temp-discord-5',
      }],
      effect: '<span class="effect__bubble">Class Bonus</span><span class="effect__label">On Enter:</span> Put a <span class="effect__label">buff</span> counter on another target ally you control. If that ally is a Beast, put two <span class="effect__label">buff</span> counters on it instead.<br><span class="effect__bubble">Class Bonus</span><span class="effect__label">Floating Memory</span>',
      effect_raw: 'todo_raw',
      element: 'NORM',
      flavor: 'todo flavor',
      last_update: '2023-01-30T22:00:00.000Z',
      level: null,
      life: 1,
      name: 'Young Beastbonder',
      power: 1,
      related_ids: null,
      slug: 'temp-discord-5',
      speed: null,
      subtypes: ['TAMER', 'HUMAN'],
      types: ['ALLY'],
      uuid: 'temp-discord-5',
    }],
  }
])

export default nonIndexSets;